my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: rja95216

      # User/password auth
      user: dkr5ud@virginia.edu
      password: DS5111dkr5ud

      role: DS5111_DBT
      database: DATA_SCIENCE
      warehouse: COMPUTE_WH
      schema: dkr5ud_RAW
      threads: 1
      client_session_keep_alive: False
      query_tag: dkr5ud_tag

      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None